"""Pydantic schemas for inbound risk assessment and telemetry requests."""
from typing import Optional, Literal
from pydantic import BaseModel, Field


class DeviceTelemetry(BaseModel):
    profile: Literal["known_trusted", "new_fingerprint", "emulated_rooted"] = Field(
        default="known_trusted",
        description="Device environment and fingerprint classification."
    )
    canvas_hash: Optional[str] = Field(
        default=None,
        description="Opaque WebGL/canvas hardware entropy hash."
    )
    is_rooted_or_jailbroken: bool = Field(
        default=False,
        description="Device integrity status."
    )


class NetworkTelemetry(BaseModel):
    type: Literal["residential", "datacenter_vpn", "tor_exit"] = Field(
        default="residential",
        description="IP classification from threat intelligence feeds."
    )
    ip_address: Optional[str] = Field(
        default="127.0.0.1",
        description="Origin IP address (used for lookup, never stored alongside PII)."
    )
    country_code: Optional[str] = Field(
        default="NG",
        description="ISO 3166-1 alpha-2 country code."
    )


class TravelLocation(BaseModel):
    latitude: float
    longitude: float
    timestamp_epoch_sec: float


class TravelTelemetry(BaseModel):
    distance_km: float = Field(
        default=0.0,
        ge=0,
        description="Calculated or provided geographic distance between consecutive session coordinates."
    )
    time_delta_hours: Optional[float] = Field(
        default=1.0,
        gt=0,
        description="Elapsed time in hours between consecutive sessions."
    )
    previous_location: Optional[TravelLocation] = None
    current_location: Optional[TravelLocation] = None


class BehaviorTelemetry(BaseModel):
    typing_profile: Literal["natural", "deviated", "robotic_paste"] = Field(
        default="natural",
        description="Passive typing cadence and flight-time variance."
    )
    flight_time_variance_ms: Optional[float] = Field(
        default=38.5,
        ge=0,
        description="Standard deviation of keydown-to-keyup interval."
    )


class TransactionTelemetry(BaseModel):
    amount: float = Field(
        default=45000.0,
        ge=0,
        description="Transaction or transfer nominal value."
    )
    currency: str = Field(
        default="NGN",
        description="ISO 4217 Currency Code."
    )
    account_id: Optional[str] = Field(
        default="acc_default",
        description="Opaque account identifier for velocity tracking."
    )


class RiskEvaluationRequest(BaseModel):
    user_id: Optional[str] = Field(default="usr_82931", description="Opaque user identifier")
    customer_id: Optional[str] = Field(default=None, description="Alias for user_id")
    telemetry_token: Optional[str] = Field(
        default=None,
        description="Opaque client telemetry token (td_tok_...) generated by trustdna.js"
    )

    device: DeviceTelemetry = Field(default_factory=DeviceTelemetry)
    network: NetworkTelemetry = Field(default_factory=NetworkTelemetry)
    travel: TravelTelemetry = Field(default_factory=TravelTelemetry)
    behavior: BehaviorTelemetry = Field(default_factory=BehaviorTelemetry)
    transaction: TransactionTelemetry = Field(default_factory=TransactionTelemetry)
