"""TrustDNA Official Python Client."""
import time
from typing import Optional, Dict, Any
import requests

from .models import RiskDecision, Subscores
from .exceptions import (
    TrustDNAError,
    AuthenticationError,
    InvalidTelemetryTokenError,
    APIConnectionError
)


class RiskResource:
    def __init__(self, client: "TrustDNAClient"):
        self._client = client

    def evaluate(
        self,
        customer_id: str,
        telemetry_token: Optional[str] = None,
        amount: Optional[float] = None,
        currency: str = "USD",
        custom_signals: Optional[Dict[str, Any]] = None,
        device: Optional[Dict[str, Any]] = None,
        network: Optional[Dict[str, Any]] = None,
        travel: Optional[Dict[str, Any]] = None,
        behavior: Optional[Dict[str, Any]] = None
    ) -> RiskDecision:
        """
        Evaluates risk on a transaction or user action.
        
        Args:
            customer_id: Unique identifier for the end user/customer.
            telemetry_token: Opaque token generated by client `trustdna.js` collector.
            amount: Transaction monetary value.
            currency: Currency code (e.g. "USD", "EUR").
            custom_signals: Custom metadata key-values.
            device, network, travel, behavior: Optional explicit vectors.
            
        Returns:
            RiskDecision object with .trust_score, .decision ("allow"|"challenge"|"block"), and .reasons.
        """
        payload: Dict[str, Any] = {
            "customer_id": customer_id,
            "telemetry_token": telemetry_token,
            "transaction": {
                "amount": amount or 0.0,
                "currency": currency,
                "is_first_time_user": False
            }
        }
        
        if device:
            payload["device"] = device
        if network:
            payload["network"] = network
        if travel:
            payload["travel"] = travel
        if behavior:
            payload["behavior"] = behavior
        if custom_signals:
            payload["transaction"]["custom_signals"] = custom_signals

        response = self._client._post("/risk/evaluate", payload)
        
        return RiskDecision(
            customer_id=response.get("customer_id", customer_id),
            trust_score=response.get("trust_score", 0.0),
            decision=response.get("decision", "challenge").lower(),
            reasons=response.get("reasons", []),
            subscores=Subscores(**response.get("subscores", {
                "device_health": 0.0,
                "network_reputation": 0.0,
                "travel_velocity": 0.0,
                "behavioral_biometrics": 0.0,
                "financial_velocity": 0.0
            })),
            latency_ms=response.get("latency_ms", 0.0),
            w3c_trace_id=response.get("w3c_trace_id")
        )


class TrustDNAClient:
    """
    TrustDNA Client for Python.
    
    Usage:
        import trustdna
        
        client = trustdna.TrustDNAClient(secret_key="td_sec_live_...")
        decision = client.risk.evaluate(
            customer_id="usr_1028",
            telemetry_token="td_tok_...",
            amount=1500.0
        )
        if decision.decision == "block":
            raise PermissionDenied("Transaction blocked by TrustDNA")
    """

    def __init__(
        self,
        secret_key: str,
        base_url: str = "http://localhost:8000/api/v1",
        timeout: float = 2.0
    ):
        if not secret_key:
            raise AuthenticationError("TrustDNA secret key must be provided (e.g. td_sec_...)")
        
        self.secret_key = secret_key
        self.base_url = base_url.rstrip("/")
        self.timeout = timeout
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {secret_key}",
            "User-Agent": "TrustDNA-Python-SDK/1.0.0",
            "Content-Type": "application/json"
        })
        
        self.risk = RiskResource(self)

    def _post(self, endpoint: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        url = f"{self.base_url}{endpoint}"
        try:
            res = self.session.post(url, json=payload, timeout=self.timeout)
            if res.status_code == 401:
                raise AuthenticationError("Invalid or revoked TrustDNA Secret Key.")
            if res.status_code >= 400:
                err_msg = getattr(res, "text", str(res.status_code))
                raise TrustDNAError(f"TrustDNA API error ({res.status_code}): {err_msg}")
            return res.json()

        except requests.exceptions.Timeout:
            raise APIConnectionError("TrustDNA risk decision timed out.")
        except requests.exceptions.ConnectionError as e:
            raise APIConnectionError(f"Failed to connect to TrustDNA engine at {self.base_url}: {e}")
